### PR TITLE
Updating default value description to match actual default value

### PR DESCRIPTION
**Pull request by joshuabalduff**
## what

`default_route_table_association` and `default_route_table_propagation` are set to disable so the description should reflect default values that to avoid possible confusion. 

## why

So it matches :) unless the default value really should be enable

### CODE REVIEW

**Comment by Gowiem** [comment]
@joshuabalduff friendly ping on this work -- can you follow the readme instructions I outlined above and we'll get this shipped.

**Comment by hans-d** [comment]
#38

**Comment by hans-d** [comment]
@Gowiem can we make this a patch release?

**Comment by Gowiem** [comment]
@hans-d hm... patch vs no-release here is interesting. I see this as just a docs fix, which means there is no real patch. But I can see the point as we'd want people to download the correct docs to their local module. I'm fine with patch.

**Review by hans-d — APPROVED** [review]
Goven that is was reviewed before

**Pull request merged**
